<?php

include_once('atrium_searchlight.features.inc');

/**
 * Implementation of hook_views_api().
 */
function atrium_searchlight_views_api() {
  return array('api' => 2);
}

/**
 * Implementation of hook_views_default_views_alter().
 */
function atrium_searchlight_views_default_views_alter(&$views) {
  if (isset($views['atrium_search'])) {
    $view = $views['atrium_search'];

    $filters = $view->display['default']->display_options['filters'];
    // Remove the created date filter.
    if (isset($filters['created'])) {
      unset($filters['created']);
    }
    // Add facets filter.
    $filters['facets'] = array(
      'id' => 'facets',
      'table' => 'searchlight',
      'field' => 'facets',
    );
    $view->display['default']->display_options['filters'] = $filters;

    // Use AJAX.
    $view->display['default']->display_options['use_ajax'] = TRUE;
    $views[$view->name] = $view;
  }

  if (isset($views['atrium_members'])) {
    $view = $views['atrium_members'];
    $view->display['default']->display_options['filters'] = $view->display['default']->display_options['filters'] + array(
      'facets' => array(
        'id' => 'facets',
        'table' => 'searchlight',
        'field' => 'facets',
      ),
      'search' => array(
        'operator' => '=',
        'value' => '',
        'group' => '0',
        'exposed' => TRUE,
        'expose' => array(
          'operator' => '',
          'identifier' => 'search',
          'label' => 'Search',
          'optional' => 1,
          'single' => 1,
          'remember' => 0,
        ),
        'hideEmpty' => 0,
        'matchMode' => '0',
        'id' => 'search',
        'table' => 'searchlight',
        'field' => 'search',
        'relationship' => 'none',
      ),
    );
    $views[$view->name] = $view;
  }
}
